name:                arbor-monad-counter
version:             1.0.0
github:              "packetloop/arbor-monad-counter"
license:             MIT
category:            Services
author:              Tyler Durden
maintainer:          tyler.durden@arbor.net
copyright:           Arbor Networks

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on Github at <https://github.com/packetloop/arbor-monad-counter#readme>

default-extensions:
- BangPatterns
- FlexibleContexts
- FlexibleInstances
- GeneralizedNewtypeDeriving
- MultiParamTypeClasses
- OverloadedStrings
- TupleSections

dependencies:
- base >=4.7 && <5
- arbor-monad-logger
- containers
- datadog
- generic-lens
- lens
- MissingH
- stm
- text
- time
- transformers

library:
  source-dirs: src
  exposed-modules:
    - Arbor.Monad.Counter.Handle
    - Arbor.Monad.Counter.Type
  ghc-options:
    - -Wall
    - -Wcompat
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wredundant-constraints

tests:
  arbor-monad-counter-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - arbor-monad-counter
    - hspec
    - hedgehog
    - hw-hspec-hedgehog
    - template
