resolver: lts-12.1

packages:
- .

- location:
    git: git@github.com:packetloop/arbor-datadog.git
    commit: 16988a60daa7d9b3ffe8df4b37b2360a2dd5bc12
  extra-dep: true

extra-deps:
- template-0.2.0.10
