resolver: lts-11.17

packages:
- .
- location:
    git: git@github.com:packetloop/datadog.git
    commit: 74c4ef963d7d455ecaed5de4c53249776abdf8e9
  extra-dep: true
- location:
    git: git@github.com:packetloop/arbor-monad-logger.git
    commit: 86f1efc88d1c5a3ff917c39a03cf4ad23a1473f3
  extra-dep: true
