resolver: lts-12.10

packages:
- .

- location:
    git: git@github.com:packetloop/arbor-datadog.git
    commit: 317f6d2a8b29fc807c98e69d9fabc428b635e5f1
  extra-dep: true

extra-deps:
- template-0.2.0.10
